### PR TITLE
Telugu

### PR DESCRIPTION
**Pull request by FredWh1b**
Hiya Qingxia

Here's the Telugu data. As always, let me know if there's a suggestion regarding formatting that you'd suggest!

I've not bothered to show the position of the negation, since the scope of the negation doesn't seem to have any real effect on the interpretation of the modal. 

Fred.

### CODE REVIEW

**Review by shanest — CHANGES_REQUESTED** [review]
Hi Fred,

Thanks for this!  Can you update the `syntactically_negated` column?  As per a meeting awhile ago, we are now using a three-way classification: `no`, and then `low`, and `high` for whether the negation scopes below or above the modal.  Let us know if you have questions about this :)

All my best,
Shane

**Comment by FredWh1b** [comment]
Ah, I thought that this could be a problem. I was going to mention in the comment before submitting... but ended up not;

I realise that this was the new plan for the conversion, but for the most part - both me and Wataru weren't entirely sure whether to analyse the negative positions as above/below in some of these negative cases, specifically with respect to both syntactic position and semantic scope (I also wasn't sure which one is required) 

but, basically - in some of these cases, the negative modals themselves seem to also encode some sort of negative force (particularly the le case that we saw), and we didn't really want to be committal to saying above or below because it wasn't really clear from our data, or the literature. 

I did do a version just putting these ones as "?", when we weren't too clear? Would that be appropriate?

**Comment by FredWh1b** [comment]
(Effectively, I reverted to the previous method here just to avoid answering the question for some of these modals and thought to keep it uniform throughout)

**Comment by shanest** [comment]
Ah, gotcha!  I think for those edge cases then a "?" and additionally a comment in the "notes" column would be perfect :)

**Comment by wigwit** [comment]
Hi Fred!

There are some inconsistency with the current database so I am trying to unify the values by updating the [readme.md](https://github.com/CLMBRs/modal-typology/blob/master/README.md). I think we decided the final version to be `[high,low,no]`, therefore no further changes required. Sorry about the confusion. Thank you so much for your contribution.

Best,
Qingxia

**Pull request merged**
