### PR TITLE
Turkish pull

### PR DESCRIPTION
**Pull request by JamesE6**
adding modals and metadata for Turkish

### CODE REVIEW

**Comment by JamesE6** [comment]
Adding Turkish and Korean

**Comment by wigwit** [comment]
Nice work! I have a small comment on Turkish expression -[y]abil/[y]ebil. Your file has put this expression as _bil. I think this is nice generalization but it would be nice if you could mention that the actual form is [abil/ebil] and they have some phonological alternation in regards to vowel harmony. Another comment is that I noticed you put -ama- as a separate expression from -abil/ebil but in the notes -ama- is seen as the negated form of -abil so I think it would be better to put -ama- as full form of expression abil/ebil in negative context. 

And nice job on Korean! There is a small question I would like to ask. You have put [philyo- eps-] instead of [philyo.nun- eps-] as the expression where the omitted part 'nun' is a negative affix.  I am just curious as in why you choose to make such decision. You do not have to modify anything for this.

Thank you again for your work to this!

**Comment by JamesE6** [comment]
Hi Qingxia, sorry this took so long. Should be corrected now.

The reason I listed [philyo- eps-] is because our data elicited both philyoNUN eps-ta (a negative existential) and philyoTUN eps-ta (which seems to be more adjectival). It was not possible to separate the two based on our questionnaire, so I included them as variants of a core modal expression [philyo- eps-] with additional notes.

Turkish should be fixed now. I also updated Vietnamese to include notes on whether the negation of the expression scopes above or below the modal core. Yes/No was enough to cover the range of negation strategies for Turkish and Korean.

**Comment by wigwit** [comment]
Thank you so much for the modification! Good work!

**Pull request merged**
